package com.example.orderappct5c

enum class Message {
    USERNAME_EMPTY,
    PASSWORD_EMPTY,
    NO_INTERNET_CONNECTION,
    SIGN_UP_FAIL,
    LOGIN_FAIL,
    SERVER_BREAKDOWN,
    ADDED_FAIL,
    ADD_SUCCESSFULLY,
    ORDER_SUCCESSFULLY,
    ORDER_FAIL,
    CANCELLED_FAIL,
    LOAD_ERROR,
    REMOVED_FAIL,
    MODIFIED_FAIL,
    RESET_FAIL
}